# Generated by Django 5.2.10 on 2026-01-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksection',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
