# Generated by Django 5.2.10 on 2026-01-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_worksection_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/cv/'),
        ),
    ]
